---
services:

  memcached:
    image: memcached:1.6.38-alpine3.21
    container_name: memcached
    environment:
      MEMCACHED_MAX_ITEM_SIZE: 36
      MEMCACHED_MAX_CONNECTIONS: 1
      MEMCACHED_MEMORY_LIMIT: 64
    ports:
    - '11211:11211'

  taa:
    build:
      context: .
    image: xchem/fragalysis-ispyb-target-access-authenticator:latest
    container_name: taa
    environment:
      ESS_MEMCACHED_LOCATION: memcached
    ports:
    - '8080:8080'
    depends_on:
      memcached:
        condition: service_started
