---
# Extends the base services file
# and provides a 'TAA_SSH_PASSWORD'
services:

  memcached:
    extends:
      file: base-services.yml
      service: memcached

  taa:
    extends:
      file: base-services.yml
      service: taa
    environment:
      TAA_SSH_PASSWORD: ${TAA_SSH_PASSWORD}
