---
services:

  memcached:
    image: memcached:1.6.38-alpine3.21
    container_name: memcached
    environment:
      MEMCACHED_MAX_ITEM_SIZE: 8000
      MEMCACHED_MAX_CONNECTIONS: 1
      MEMCACHED_MEMORY_LIMIT: 64
    ports:
    - '11211:11211'

  taa:
    build:
      context: .
    image: xchem/fragalysis-ispyb-target-access-authenticator:latest
    container_name: taa
    environment:
      # If you expected to be able to connect to the ISPyB SSH service,
      # populate the following using a suitable .env file
      TAA_ISPYB_HOST: ${TAA_ISPYB_HOST}
      TAA_ISPYB_PORT: ${TAA_ISPYB_PORT}
      TAA_ISPYB_USER: ${TAA_ISPYB_USER}
      TAA_ISPYB_PASSWORD: ${TAA_ISPYB_PASSWORD}
      TAA_SSH_HOST: ${TAA_SSH_HOST}
      TAA_SSH_USER: ${TAA_SSH_USER}
      # Non-sensitive configuration
      TAA_SSH_PRIVATE_KEY_FILENAME: /home/taa/ssh-private-key
      TAA_QUERY_KEY: blob1234
      TAA_MEMCACHED_LOCATION: memcached
      TAA_CACHE_EXPIRY_MINUTES: 2
    ports:
    - '8080:8080'
    volumes:
      # You're expected to have an SSH private key file in your .ssh directory
    - ${HOME}/.ssh/fragalysis-stack:/home/taa/ssh-private-key
    depends_on:
      memcached:
        condition: service_started
