---
name: build

# Actions that take place after every commit that's not on either the
# staging ore production branches.

# ---------------
# Control secrets
# ---------------
#
# (none)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# (none)

on:
  push:
    tags-ignore:
    - '**'

env:
  # The following 'defaults' are used in the 'Initialise workflow variables' step,
  # which creates 'outputs' for use in steps and jobs that follow it.
  # The values set here are used unless a matching secret is found.
  # Secrets are the way users dynamically control the behaviour of this Action.
  #
  #   For Jobs conditional on the presence of a secret see this Gist...
  #   https://gist.github.com/jonico/24ffebee6d2fa2e679389fac8aef50a3
  NAMESPACE: xchem

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v5
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      uses: docker/build-push-action@v6
      with:
        tags: xchem/fragalysis-ispyb-target-access-authenticator:latest
